<nav>
	<ul>
		<li><a href="#">Home</a></li>
		<li><a href="#">Lectures</a>
			<ul>
				<li><a href="#">Week 1</a></li>
				<li><a href="#">Week 2</a></li>
				<li><a href="#">Week 3</a></li>
			</ul>
		</li>
		<li><a href="#">Exercises</a>
			<ul>
				<li><a href="#">Exercise 1</a></li>
				<li><a href="#">Exercise 2</a></li>
				<li><a href="#">Exercise 3</a></li>
			</ul>
		</li>
		<li><a href="#">Assignments</a>
			<ul>
				<li><a href="#">Assignment 1</a></li>
				<li><a href="#">Assignment 2</a></li>
				<li><a href="#">Assignment 3</a></li>
			</ul>
		</li>
		<li><a href="#">Resources</a>
			<ul>
				<li><a href="#">Resource 1</a></li>
				<li><a href="#">Resource 2</a></li>
				<li><a href="#">Resource 3</a></li>
			</ul>
		</li>
		<li><a href="#">Blog</a></li>
	</ul>
</nav>